### ISSUE TITLE
"r this" should create multiple mail reminders when multiple emails are selected

### ISSUE THREAD

**Issue by dabrahams** [surrealroad/alfred-reminders#22]
Subject says all.  Why restrict this to one-at-a-time?

Also, it would be awesome if the mail could be archived as part of that action.

**Comment by surrealroad** [comment]
the reason it does one at a time, is because when you're in conversations view, mail doesn't actually say what's selected accurately.

having the email automatically archived I feel is too much of a specific request, some people won't want it to do that.

You can always fork the workflow and edit https://github.com/surrealroad/alfred-reminders/blob/master/app_Mail.scpt `getBody()` to suit your needs
